name: repository_search
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # http通信
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # モデル用
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  # 状態管理
  flutter_riverpod: ^2.4.4

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # モデル用
  json_serializable: ^6.7.1

  # 自動生成
  build_runner: ^2.4.6

  # テスト用
  mockito: ^5.4.2

flutter:
  uses-material-design: true
